### PR TITLE
Update Graylog Vagrant box to 2.3.x

### LINKED ISSUE #44: Update Graylog box to 2.x

### PR DESCRIPTION
**Pull request by bernd**
This is a work in progress to update the icinga2x-graylog Vagrant box to Graylog 2.3.x.

- Updated the Elasticsearch Puppet module to make it work with Elasticsearch 5.4.x

fixes #44

### CODE REVIEW

**Comment by dnsmichi** [comment]
I had to update the elasticsearch puppet module in #76. So I've picked #78 into a separate PR, and rebased the update-graylog branch for this PR @bernd - now it is just one commit ahead of master atm.

**Comment by bernd** [comment]
@dnsmichi Thank you! <3

**Comment by dnsmichi** [comment]
@bernd since 2.3 is released, we could update the PR once more to get it merged, please? :)

**Comment by dnsmichi** [comment]
Updated the branch and added patches to make it work again with 2.3.

**Pull request merged**
