### PR TITLE
Hiera configures the primary listen interface, no magic ifname lookup anymore

### LINKED ISSUE #141: ipaddress_eth1 Puppet fact not available with VirtualBox ("predictable interface names")
If you try to open the host or service detail page, the page shows only the following error message:

 ``
Could not resolve host: icingaweb2; Name or service not known
``

The error is caused by the graphite module in whose configuration the URL is missing / broken.

**/etc/icingaweb2/modules/graphite/config.ini:**
```ini
[graphite]
url = "http://:8003"

[ui]
default_time_range = "5"
default_time_range_unit = "minutes"
disable_no_graphs_found = "0"
```

## Expected Behavior
Host or service detail page is shown.

## Current Behavior
Both pages terminate with the error message.

## Possible Solution
Set the hostname to the IP 192.168.33.5

## Steps to Reproduce (for bugs)
1. Clone icinga-vangrant git repository
2. cd icinga-vagrant/standalone && vagrant up

## Context
GIT master

## Your Environment

* Vagrant version (`vagrant -v`): 2.0.2
* Box name: standalone
* Release version: git master
* Operating system: Fedora 27
* Provider (VirtualBox, Parallels, libvirt): VirtualBox

### PR DESCRIPTION
**Pull request by dnsmichi**
Parallels as Vagrant provider ignores "predictable interface names" coming with CentOS7.
The VirtualBox provider from Vagrant itself enables this as default with > 1.8.3.

Therefore we have `enp0s8` vs `eth1`.

Doesn't work reliably, and therefore `hierdata/node/{::fqdn}.yaml` defines the hostonly
primary listen interface where needed. This is possible with interpolation in Hiera 5 by
doing a reverse lookup() call.

fixes #141

### CODE REVIEW

**Comment by dnsmichi** [comment]
@nbuchwitz please test it as well.

I still need to test whether Parallels now works, or not.

**Comment by nbuchwitz** [comment]
@dnsmichi LGTM :+1:

**Comment by nbuchwitz** [comment]
Tested with Fedora 27, VirtualBox 5.2.8 & Vagrant 2.0.2

**Comment by dnsmichi** [comment]
Thanks. Parallels works too. It is always funny to bring `vnic2` and `vboxnet0` up and down between Parallels and Virtualbox until you can access 192.168.33.5 again :)

**Comment by dnsmichi** [comment]
macOS High Sierra, Vagrant 2.0.1, VirtualBox 5.1.30r118389, Parallels version 13.2.0 (43213)

**Pull request merged**
