### PR TITLE
Integrate Icinga Reporting v0.9.0

### PR DESCRIPTION
**Pull request by dnsmichi**
https://icinga.com/2019/04/17/releasing-icinga-reporting-for-early-adopters/

- [x] Reporting and IDOReports module including dependency handling: reactbundle, ipl, pdfexport
- [x] Configuration and resources done with Puppet, import schema files into IDO database too
- [x] Setup Chrome headless for PDF exports

The reports in the screenshots below need to be done manually, by creating them and selecting timeframes. I'm not sure yet how to feed report data into MySQL for example config.

vagrant_icingaweb2_reporting

Screen Shot 2019-04-17 at 15 10 20

This is the first early adopter version. Don't expect
everything to work properly - open product specific issues over at

https://github.com/icinga/icingaweb2-module-idoreports
https://github.com/icinga/icingaweb2-module-reporting

### CODE REVIEW

**Comment by dnsmichi** [comment]
Re-run and provisioned again with the latest fixes, works fine.

**Comment by mdeguzis** [comment]
Thanks so much!!!

**Comment by ADeeeee** [comment]
Pardon me, is there any support plan for icingaweb2 with PostgreSQL in the future?

**Comment by mdeguzis** [comment]
@ADeeeee there are GitHub issues I submitted already for this. It's being worked on as far as I know.

**Comment by dnsmichi** [comment]
> Pardon me, is there any support plan for icingaweb2 with PostgreSQL in the future?

That is why I have linked the corresponding GitHub projects. The Vagrant boxes are for demo purposes and just install several components.

> This is the first early adopter version. Don't expect
> everything to work properly - open product specific issues over at
> 
> https://github.com/icinga/icingaweb2-module-idoreports
> https://github.com/icinga/icingaweb2-module-reporting

**Pull request merged**
